#!/usr/bin/env bash
# script that pings an IP address passed as an argument

# Check if an argument (IP address) is provided
if [ -z "$1" ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Store the provided IP address in a variable
IP_ADDRESS="$1"

# Ping the IP address 5 times
ping -c 5 "$IP_ADDRESS"
