#!/usr/bin/env bash
# Script that that configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

# Backup the current /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Add or replace the entry for localhost
sudo sed -i '/localhost/c\127.0.0.2 localhost' /etc/hosts

# Add or replace the entry for facebook.com
if grep -q "facebook.com" /etc/hosts; then
    sudo sed -i '/facebook.com/c\8.8.8.8 facebook.com' /etc/hosts
else
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
fi

#------- SCRIPT TO RESTORE BACK !!! -----------
# Restore the original /etc/hosts file from the backup
# if [ -f /etc/hosts.bak ]; then
#   sudo cp /etc/hosts.bak /etc/hosts
#   echo "The /etc/hosts file has been restored to its original state."
# else
#   echo "Backup file /etc/hosts.bak not found. Cannot restore original settings."
# fi
#---------------------------------------------
